ALTER TABLE games MODIFY executable VARCHAR(255) NULL;
ALTER TABLE games ADD COLUMN cover_url VARCHAR(1000) NULL AFTER description;
ALTER TABLE games ADD COLUMN banner_url VARCHAR(1000) NULL AFTER cover_url;
ALTER TABLE games ADD COLUMN local_cover_path VARCHAR(500) NULL AFTER banner_url;
ALTER TABLE games ADD COLUMN local_banner_path VARCHAR(500) NULL AFTER local_cover_path;

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  token_hash CHAR(64) NOT NULL UNIQUE,
  expires_at DATETIME NOT NULL,
  used_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_reset_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_reset_expiry (expires_at, used_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DELETE FROM games WHERE slug IN ('neon-horizon','echoes-of-anatolia','lime-protocol');

INSERT INTO games
(name,slug,short_description,description,cover_path,banner_path,local_cover_path,local_banner_path,steam_app_id,epic_catalog_id,executable,process_name,access_type,translation_percent,supported_stores,is_active)
VALUES
('Assassin''s Creed II','assassins-creed-ii','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Assassin''s Creed Brotherhood','assassins-creed-brotherhood','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Assassin''s Creed Revelations','assassins-creed-revelations','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Battlefield 3','battlefield-3','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Dead Island 2','dead-island-2','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Devil May Cry 5','devil-may-cry-5','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('LEGO Batman Legacy of the Dark Knight','lego-batman-legacy-of-the-dark-knight','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('LEGO Marvel Super Heroes 2','lego-marvel-super-heroes-2','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Mafia: The Old Country','mafia-the-old-country','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Resident Evil 0 HD Remaster','resident-evil-0-hd-remaster','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Resident Evil 1 (1996)','resident-evil-1-1996','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Resident Evil 2 (1998)','resident-evil-2-1998','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Resident Evil 2 Remake','resident-evil-2-remake','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Resident Evil 3 (1999)','resident-evil-3-1999','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Resident Evil 3 Remake','resident-evil-3-remake','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Resident Evil 4 Remake','resident-evil-4-remake','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Resident Evil 4 Ultimate HD Edition','resident-evil-4-ultimate-hd-edition','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Resident Evil 5','resident-evil-5','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Resident Evil 6','resident-evil-6','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Resident Evil 7','resident-evil-7','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Resident Evil HD Remaster','resident-evil-hd-remaster','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Resident Evil Code: Veronica (2000)','resident-evil-code-veronica-2000','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Resident Evil Operation Raccoon City','resident-evil-operation-raccoon-city','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Resident Evil Revelations','resident-evil-revelations','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Resident Evil Revelations 2','resident-evil-revelations-2','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Resident Evil Requiem','resident-evil-requiem','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Resident Evil Village','resident-evil-village','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Real Space 3','real-space-3','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Serious Sam 2','serious-sam-2','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Silent Hill 1','silent-hill-1','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Silent Hill 2 Remake','silent-hill-2-remake','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Silent Hill 3','silent-hill-3','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Silent Hill 4','silent-hill-4','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('The Walking Dead: The Telltale Definitive Series','the-walking-dead-the-telltale-definitive-series','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Winx Club: The Magic Is Back','winx-club-the-magic-is-back','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Assassin''s Creed Mirage','assassins-creed-mirage','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('Assassin''s Creed Black Flag Resynced','assassins-creed-black-flag-resynced','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1),
('The Amazing Spider-Man 1','the-amazing-spider-man-1','Türkçe yama kütüphane kaydı.','Türkçe yama dosyası ve destek bilgileri yönetim panelinden yayınlanacaktır.','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg','/assets/placeholders/cover-generic.svg','/assets/placeholders/banner-generic.svg',NULL,NULL,NULL,NULL,'free',0,JSON_ARRAY('manual'),1)
ON DUPLICATE KEY UPDATE name=VALUES(name),is_active=1;

UPDATE loader_config SET app_name='Animus Türkçe Yama',library_title='Oyun Kütüphanesi' WHERE id=1;
